/*
 * aNNiMON 2013 
 * http://annimon.com/
 */

package com.annimon.scheduler.gui;

/**
 *
 * @author aNNiMON
 */
public class SchedulerMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form SchedulerMenuPanel
     */
    public SchedulerMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableButtonsPanel = new javax.swing.JPanel();
        controlButtonsPanel = new javax.swing.JPanel();
        helpButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tableButtonsPanel.setLayout(new javax.swing.BoxLayout(tableButtonsPanel, javax.swing.BoxLayout.PAGE_AXIS));
        add(tableButtonsPanel, java.awt.BorderLayout.NORTH);

        controlButtonsPanel.setLayout(new javax.swing.BoxLayout(controlButtonsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        helpButton.setText("Помощь");
        helpButton.setMaximumSize(new java.awt.Dimension(150, 23));
        helpButton.setMinimumSize(new java.awt.Dimension(70, 23));
        controlButtonsPanel.add(helpButton);

        aboutButton.setText("О программе");
        aboutButton.setMaximumSize(new java.awt.Dimension(150, 23));
        aboutButton.setMinimumSize(new java.awt.Dimension(70, 23));
        controlButtonsPanel.add(aboutButton);

        exitButton.setText("Выход");
        exitButton.setMaximumSize(new java.awt.Dimension(150, 23));
        exitButton.setMinimumSize(new java.awt.Dimension(70, 23));
        controlButtonsPanel.add(exitButton);

        add(controlButtonsPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JPanel controlButtonsPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JPanel tableButtonsPanel;
    // End of variables declaration//GEN-END:variables
}
